"""+chat

Revision ID: 3890858deba0
Revises: c9b7d4a1b2ce
Create Date: 2026-03-09 21:10:41.843082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3890858deba0'
down_revision: Union[str, Sequence[str], None] = 'c9b7d4a1b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # В разных средах LightRAG может создавать разные индексы,
    # поэтому безопасно удаляем только таблицы (с индексами каскадом).
    lightrag_tables = (
        'lightrag_vdb_entity',
        'lightrag_llm_cache',
        'lightrag_relation_chunks',
        'lightrag_doc_full',
        'lightrag_full_entities',
        'lightrag_doc_chunks',
        'lightrag_entity_chunks',
        'lightrag_doc_status',
        'lightrag_vdb_chunks',
        'lightrag_vdb_relation',
        'lightrag_full_relations',
    )
    for table_name in lightrag_tables:
        op.execute(sa.text(f'DROP TABLE IF EXISTS "{table_name}" CASCADE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightrag_full_relations',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('relation_pairs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_full_relations_pk'))
    )
    op.create_index(op.f('idx_lightrag_full_relations_workspace_id'), 'lightrag_full_relations', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_full_relations_id'), 'lightrag_full_relations', ['id'], unique=False)
    op.create_table('lightrag_vdb_relation',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_vdb_relation_pk'))
    )
    op.create_index(op.f('idx_lightrag_vdb_relation_workspace_id'), 'lightrag_vdb_relation', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_relation_id'), 'lightrag_vdb_relation', ['id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_relation_hnsw_cosine'), 'lightrag_vdb_relation', ['content_vector'], unique=False, postgresql_ops={'content_vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('lightrag_vdb_chunks',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_doc_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('chunk_order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_vdb_chunks_pk'))
    )
    op.create_index(op.f('idx_lightrag_vdb_chunks_workspace_id'), 'lightrag_vdb_chunks', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_chunks_id'), 'lightrag_vdb_chunks', ['id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_chunks_hnsw_cosine'), 'lightrag_vdb_chunks', ['content_vector'], unique=False, postgresql_ops={'content_vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('lightrag_doc_status',
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_summary', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunks_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunks_list', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_doc_status_pk'))
    )
    op.create_index(op.f('idx_lightrag_doc_status_workspace_updated_at'), 'lightrag_doc_status', ['workspace', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_workspace_status_updated_at'), 'lightrag_doc_status', ['workspace', 'status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_workspace_status_created_at'), 'lightrag_doc_status', ['workspace', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_workspace_id'), 'lightrag_doc_status', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_workspace_file_path'), 'lightrag_doc_status', ['workspace', 'file_path'], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_workspace_created_at'), 'lightrag_doc_status', ['workspace', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_track_id'), 'lightrag_doc_status', ['track_id'], unique=False)
    op.create_index(op.f('idx_lightrag_doc_status_id'), 'lightrag_doc_status', ['id'], unique=False)
    op.create_table('lightrag_entity_chunks',
    sa.Column('id', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chunk_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_entity_chunks_pk'))
    )
    op.create_index(op.f('idx_lightrag_entity_chunks_workspace_id'), 'lightrag_entity_chunks', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_entity_chunks_id'), 'lightrag_entity_chunks', ['id'], unique=False)
    op.create_table('lightrag_doc_chunks',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_doc_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('chunk_order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('llm_cache_list', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_doc_chunks_pk'))
    )
    op.create_index(op.f('idx_lightrag_doc_chunks_workspace_id'), 'lightrag_doc_chunks', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_doc_chunks_id'), 'lightrag_doc_chunks', ['id'], unique=False)
    op.create_table('lightrag_full_entities',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_full_entities_pk'))
    )
    op.create_index(op.f('idx_lightrag_full_entities_workspace_id'), 'lightrag_full_entities', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_full_entities_id'), 'lightrag_full_entities', ['id'], unique=False)
    op.create_table('lightrag_doc_full',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('doc_name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_doc_full_pk'))
    )
    op.create_index(op.f('idx_lightrag_doc_full_workspace_id'), 'lightrag_doc_full', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_doc_full_id'), 'lightrag_doc_full', ['id'], unique=False)
    op.create_table('lightrag_relation_chunks',
    sa.Column('id', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chunk_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_relation_chunks_pk'))
    )
    op.create_index(op.f('idx_lightrag_relation_chunks_workspace_id'), 'lightrag_relation_chunks', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_relation_chunks_id'), 'lightrag_relation_chunks', ['id'], unique=False)
    op.create_table('lightrag_llm_cache',
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('return_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cache_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('queryparam', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_llm_cache_pk'))
    )
    op.create_index(op.f('idx_lightrag_llm_cache_workspace_id'), 'lightrag_llm_cache', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_llm_cache_id'), 'lightrag_llm_cache', ['id'], unique=False)
    op.create_table('lightrag_vdb_entity',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('workspace', 'id', name=op.f('lightrag_vdb_entity_pk'))
    )
    op.create_index(op.f('idx_lightrag_vdb_entity_workspace_id'), 'lightrag_vdb_entity', ['workspace', 'id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_entity_id'), 'lightrag_vdb_entity', ['id'], unique=False)
    op.create_index(op.f('idx_lightrag_vdb_entity_hnsw_cosine'), 'lightrag_vdb_entity', ['content_vector'], unique=False, postgresql_ops={'content_vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
