"""add chunks_count to documents

Revision ID: a6e89db8b14e
Revises: eb9694333fdd
Create Date: 2026-03-07 02:40:19.885673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e89db8b14e'
down_revision: Union[str, Sequence[str], None] = 'eb9694333fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunks_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunks_count')
    # ### end Alembic commands ###
